server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    key-store-type: PKCS12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_SERVER}
    username: root
    password: '1918'

openapi:
  service:
    url: ${PUBLIC_IP}